### ISSUE TITLE
'undefined' copied in clipboard

### ISSUE THREAD

**Issue by palashmon** [wesbos/CSS-Cursors#4]
Clicking on any of the first two or last two li's is resulting in `undefined` being copied in clipboard.

I think, this can be resolved by using logical OR (||) in */source/scripts.js* for checking `this.dataset.css` for `falsy` value like:

```
clipboardInput.value = this.dataset.css || '';
```

**P.S.** Really liked this handy site. Awesome stuff. As always, @wesbos is cool :sunglasses:

**Comment by wesbos** [comment]
Thanks a ton! You are welcome to try fix it if you like. Interested?

**Comment by palashmon** [comment]
I have added a PR. Please review it once. Thanks! :rocket:
